package domain

import "gorm.io/gorm"

type Market struct {
	gorm.Model
	Player        Player `json:"player"`
	PlayerId      uint   `json:"player_id" gorm:"default:null"`
	PlayerPrice   int64  `json:"player_price"`
	AutoGenerated bool   `json:"auto_generated" gorm:"default:0"`
	IsSold        bool   `json:"is_sold"`
}

type MarketSort struct {
	gorm.Model
	Player        Player `json:"player"`
	PlayerId      uint   `json:"player_id" gorm:"default:null"`
	PlayerPrice   int64  `json:"player_price"`
	AutoGenerated bool   `json:"auto_generated" gorm:"default:0"`
	IsSold        bool   `json:"is_sold"`
}
